AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'doc/**/*'
    - '.yardoc/**/*'

Style/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/ocr_crawler/gui/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/ocr_crawler/gui/**/*'
    - 'lib/ocr_crawler/config.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/ocr_crawler/gui/**/*'
    - 'lib/ocr_crawler/config.rb'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/ocr_crawler/gui/**/*'
    - 'lib/ocr_crawler/config.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/ocr_crawler/gui/**/*'
    - 'lib/ocr_crawler/config.rb'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'lib/ocr_crawler/gui/**/*'
